### ISSUE TITLE
Button - official support for ghost and ghost-secondary variants

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#1010]
Hi there,

I'd like to ask if it would be possible to add documentation for `ghost` variant of button and
to introduce new variant `ghost-secondary` which would be the same as `ghost` but with (front) color like the `secondary` variant.
So basically the color of text / icon is black instead of magenta in the default light theme.

We are using this quite a lot in our application I wonder maybe it could be useful for the whole community.
I could try to contribute it if there is interest in it.

```css
.button--variant-ghost-secondary {
  background: transparent;
  text-align: center;
  border-radius: var(--radius-ghost);
  border: var(--border-width-ghost) solid transparent;
  color: var(--color-ghost-secondary);
  padding-left: var(--spacing-x-ghost);
  padding-right: var(--spacing-x-ghost);
}
.button--variant-ghost-secondary:not(.button--disabled):hover {
  color: var(--color-ghost-secondary-hover);
  background-color: var(--background-ghost-hover);
}
.button--variant-ghost-secondary:not(.button--disabled):active {
  color: var(--color-ghost-secondary-active);
  background-color: var(--background-ghost-active);
}
.button--disabled.button--variant-ghost-secondary {
  color: var(--color-ghost-secondary-disabled);
}
```
