### ISSUE TITLE
Styling scale-logo when focused

### ISSUE THREAD

**Issue by mato-a** [telekom/scale#1043]
Hi there,

I have difficulty trying to change the styling of the focused `scale-logo` in the header.

In the rest of the components it is possible to change it using `--box-shadow-focus` or css rule using `::part()` syntax.
But it seems that for `scale-logo` this functionality is missing. Could you add these feature? Or is there a workaround for this?

The best I could do for now is this. The problem is that there are two focuses actually, because I am unable to reach the `a` element and it gets default focus which differs in Firefox and Chrome.
```css
scale-logo:focus {
  outline: 2px solid white;
  border-radius: 5px;
}
```
