### ISSUE TITLE
How to switch themes / design Tokens

### ISSUE THREAD

**Issue by telion2** [telekom/scale#1217]
Hi,
we are planning to introduce scale in our systems. 
For Context, we serve customers who want different themes consistent with their own. 

As far as I understood the documentation, design tokens are used to set every CSS variable that influences a scale component. 

However, I couldn't understand what a developer must do to use this functionality, and what a design Token can/should define. 

In our case, we use Vue 2 and we probably will use scale side-by-side with vuetify, as we used vuetify until now. 

I would also like to propose to add a part to the documentation that answers this question for frameworks if there are differences on how design tokens are integrated.

**Comment by acstll** [comment]
Hey @telion2, thanks for asking! I will get back to you with a detailed answer next week. Thanks for the patience 🙏

**Comment by telion2** [comment]
Friendly Reminder ;)

**Comment by acstll** [comment]
I'm truly sorry for the (still) embarrassing delay in my reply. And thanks for the friendly reminder indeed. The thing that was holding me back from almost every other task is finally done! I will post the reply you deserve next week.

**Comment by acstll** [comment]
Here it is, finally. Again, my apologies for the delay. If you need any further clarification, please let me know.

> design tokens are used to set every CSS variable that influences a scale component.

just to clarify, this is the idea, but it can happen that a component variable needs a hard-coded value.

Design tokens define the global design parameters of the system. The component tokens (or "scoped CSS variables" as we like to call them) are the "component design API". As you suggest, these variables ideally consume only design tokens. So changing the tokens affect all components in a stable and expected manner.

> I couldn't understand what a developer must do to use this functionality, and what a design Token can/should define.

Developers can override values at both of these levels (tokens and/or component variables). When you create a theme, you probably want to touch both levels. I will explain how that is technically done below.

Before moving forward, you can check the entire list of design tokens in the following links. Also [the repo is public](https://github.com/telekom/design-tokens):
- https://unpkg.com/@telekom/design-tokens@1.0.0-beta.3/dist/telekom/css/telekom-design-tokens.all.css
- https://gist.github.com/acstll/ce2927463482a01ba4928c54a57a4c7e

## Overriding tokens and variables to create a theme

The most straight-forward way is to add a CSS file to your app, that loads **after** the `@telekom/scale-components/dist/scale-components/scale-components.css` file. There you can add your overrides.

### Overriding tokens

If you wanted to change the "primary" color, you can do the following. This will replace the Telekom Magenta is ALL components:

```css
:root {
  --telekom-color-text-and-icon-primary-standard: limegreen;
  --telekom-color-text-and-icon-primary-hovered: seagreen;
  --telekom-color-text-and-icon-primary-pressed: green;
  --telekom-color-primary-standard: limegreen;
  --telekom-color-primary-hovered: seagreen;
  --telekom-color-primary-pressed: green;
}
```

If you wanted to be able to switch between themes, you can scope the overrides to a class or an attribute, instead of using `:root`:

```css
.my-green-theme {
  --telekom-color-text-and-icon-primary-standard: limegreen;
  --telekom-color-text-and-icon-primary-hovered: seagreen;
  --telekom-color-text-and-icon-primary-pressed: green;
  --telekom-color-primary-standard: limegreen;
  --telekom-color-primary-hovered: seagreen;
  --telekom-color-primary-pressed: green;
}
```

> ☝️ If you're using CSS-in-JS, there should be a method for creating global styles, like [`createGlobalStyle`](https://styled-components.com/docs/api#createglobalstyle) in the `styled-components` library.

### Overriding component's scoped CSS variables

Almost every component exposes some CSS variables. (These should be documented, but it can be that in some cases they're not. This will be fixed in an upcoming release.) Independently from if they use Shadow DOM of not.

For example, to change the border radius of the window of the Modal component, you can do this, still on that same global file:

```css
.my-green-theme scale-modal {
  --radius-window: 0;
}
```

### Dark mode

Keep in mind that if you override color variables, it's a good idea to also do it for dark mode:

```css
[data-mode="dark"].my-green-theme {
  --telekom-color-text-and-icon-primary-standard: limegreen;
  /* ... */
}
```

## Consuming tokens in other frameworks (or vanilla)

All that above is for overriding styles in Scale. You could, however, go the opposite way, and use Scale (the Telekom Design Tokens) to style or override values in another framework or your own custom designs, which is a pretty smart thing to do. That way you're not limited to the components in the Scale library. You can make your own components look Scale-like pretty easily by only consuming the tokens.

The concept of the both levels also applies here. Some frameworks allow for global customization, for instance, [Vuetify](https://vuetifyjs.com/en/styles/colors/#javascript-color-pack) (that you mentioned).

```js
// src/plugins/vuetify.js

import Vue from 'vue'
import Vuetify from 'vuetify/lib'

import { colors as lightColors } from '@telekom/design-tokens/dist/telekom/js/telekom-design-tokens.light.js'
import { colors as darkColors } from '@telekom/design-tokens/dist/telekom/js/telekom-design-tokens.dark.js'

Vue.use(Vuetify)

export default new Vuetify({
  theme: {
    themes: {
      light: {
        primary: lightColors.primary.standard,
        // ...
      },
      light: {
        primary: darkColors.primary.standard,
        // ...
      },
    },
  },
})
```

If you have loaded the `@telekom/scale-components/dist/scale-components/scale-components.css` file, all `--telekom` tokens as CSS variables are available, so you can use them anywhere:

```css
.my-custom-button {
  background: var(--telekom-color-primary-standard);
}
