### ISSUE TITLE
Dropdown turns black when prefers-color-scheme is dark, but overriden with `data-mode="light"`

### ISSUE THREAD

**Issue by jamie-magenta** [telekom/scale#1378]
**Scale Version**
3.0.0-beta.117

**Framework and version**
Angular v12

**Current Behavior**
If we override the color mode to light mode with `data-mode="light"`, but a user has its system dark mode enabled, the dropdown turns black, because the color is hardcoded into the css:
```css
.dropdown:not(.dropdown--disabled):not(.dropdown--status-error) .input__dropdown:hover {
    background-color: #1b1b1b;
}
```

Compared to a text field, this doesn't seem to be correct:
```css
.text-field:not(.text-field--disabled):not(.text-field--readonly) .text-field__control:hover {
    border-color: var(--border-color-hover);
    background-color: var(--background-color-hover);
}
```

**Expected Behavior**
Apply the same css rules to the `<select>` element as used in `<scale-text-field>`

**Code Reproduction**
A minimal reproduction case of the bug, you may fork one of the available sandboxes as a base: 
Set your `prefers-color-scheme` to dark, override it in the `<body>` element with `data-mode="light"` and hover over a `<scale-dropdown>`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 107.0.5304.88 (Official Build) (64-Bit)
