### ISSUE TITLE
some icons have default right margin

### ISSUE THREAD

**Issue by tshimber** [telekom/scale#1843]
**Scale Version**
3.0.0-beta.134

**Framework and version**
Angular 14

**Additional context**
After updating to 134 version I have lil issue: icons got some extra margin, and as far as I use them in focusable buttons, this looks not so nice. I've rewritten it, but maybe better not to put default one-side margin to icons? Not critical, I can live with it, just a remark)

![image](https://github.com/telekom/scale/assets/110041439/7aef7dd3-1a69-42b5-b07f-4a658ee9c3e1)
![image](https://github.com/telekom/scale/assets/110041439/86952aae-3bb3-4205-a71d-a4a08b46fd29)

**Comment by tshimber** [comment]
considering prev comment: i've fixed it, you need to add **iconOnly: true** to btn obj inside dataGrid. maybe somebody will face same issue

**Comment by georgwittberger-telekom-mms** [comment]
We are facing the same issue when using some specific icons inside Scale buttons. For example:

```html
<scale-button icon-only>
  <scale-icon-alert-information accessibility-title="Info"></scale-icon-alert-information>
</scale-button>
```

The icon `scale-icon-alert-information` has a right margin of 4px when it is used on a page where Radio Button Group is also loaded.

![S6vkF7unRr](https://github.com/telekom/scale/assets/64543811/be517015-69be-42de-b4e4-bd496b9cfc05)

This is caused by too general CSS selectors in the following files:

- dist/collection/components/checkbox/checkbox.css
- dist/collection/components/helper-text/helper-text.css
- dist/collection/components/radio-button/radio-button.css

They contain code like this:

```css
scale-icon-alert-information,
scale-icon-alert-error {
  color: var(--color-helper-text);
  display: flex;
  justify-content: center;
  align-items: center;
  margin-right: var(--telekom-spacing-composition-space-03);
}
```

Setting these CSS properties should be scoped to icon usages within the respective components.

We work around this issue by overriding the right margin with a more specific selector in our own CSS file:

```css
scale-button scale-icon-alert-information,
scale-button scale-icon-alert-error {
  margin-right: 0;
}
```
