### ISSUE TITLE
Telekom Brand Header: Active language switcher item not highlighted when using buttons

### ISSUE THREAD

**Issue by georgwittberger-telekom-mms** [telekom/scale#2003]
**Scale Version**

3.0.0-beta.134

**Framework and version**

React with @telekom/scale-components-react

**Current Behavior**

Active language switcher item is not highlighted in bold text when using HTML `button` element inside `scale-telekom-nav-item`.

![eL5eTC0e2F](https://github.com/telekom/scale/assets/64543811/d73d6c8a-cfc3-429e-b6e4-4c06823ce677)

**Expected Behavior**

Active language switcher item should be highlighted when using `button` as interactive element.

**Code Reproduction**

```html
<scale-telekom-nav-list slot="lang-switcher" variant="lang-switcher" alignment="right" aria-label="Language switcher">
  <scale-telekom-nav-item active>
    <button type="button" title="German" aria-label="Switch to German" role="menuitem">DE</a>
  </scale-telekom-nav-item>
</scale-telekom-nav-list>
```

**Additional context**

The attribute `aria-current="true"` is set on the `button` element correctly. It seems like the CSS selector for highlighting is simply missing that element type:

```css
.scale-telekom-nav-list[variant='lang-switcher']>.scale-telekom-nav-item>a:where([aria-current='true']) {
    font-weight: var(--telekom-typography-font-weight-extra-bold);
}
```

The selector should rather be:

```
.scale-telekom-nav-list[variant='lang-switcher']>.scale-telekom-nav-item>:where(a,button):where([aria-current='true'])
```
