### ISSUE TITLE
portalName in the brandHeader component has bulletpoint and can't be removed

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#366]
I can't style the css selector of the ul or li element.

There can't be any conflict with the access level of the selector.
I can find the styling in my index.css, but the browser doesn't apply it.

The css class of the ul is 'sector-navigation' and of the li is 'sector-navigation__portal-name'.

I don't get it.

```css
.sector-navigation, 
.sector-navigation__portal-name {
  list-style-type: none;
}
```

```jsx
import "@telekom/scale-components/dist/scale-components/scale-components.css";
import "./styles/index.css";

```
