### ISSUE TITLE
Fieldset with legend

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#518]
Hello there,

How about adding a fieldset and a legend

as example the fieldset + legend from the old html components: 

I am not sure about the border-bottom, because you dont use borders, maybe you have an idea.
```css
fieldset {
  border: 0;
  padding: 0;
  margin: 0;
  min-width: 0;
}

fieldset > legend {
  margin: 0;
  border: 0;
  color: var(--scl-color-text-additional);
  display: block;
  width: 100%;
  box-sizing: content-box;
  padding: 0 var(--scl-spacing-8) px;
  margin-bottom: var(--scl-spacing-8);
  border-bottom: 1px solid var(--scl-color-text-additional);
}

```
