### ISSUE TITLE
ScaleInputField ScaleTextArea fill height of parent

### ISSUE THREAD

**Issue by christopherGdynia** [telekom/scale#522]
Hello there,

currently I am copying layouts like form, for that I am using tailwindcss, but it'a a bit weird that the input elements are not 100% of the parent container.

Do you have a fix or a hint for me?

Thanks for your help

**Comment by christopherGdynia** [comment]
In Addition, the same goes for the width of the scale-button component

With the tailwindcss classes i am adding styles to the wrapper container, thats why the button isn't getting width 100% or display block and the input element isn't getting height 100% | 120px

**Comment by christopherGdynia** [comment]
Possible Fix:

ScaleTextArea:
```jsx 
<ScaleTextArea style={{height: "108px"}} />
```
```scss
.scale-textarea {
height: 100%;
& > textarea {
minHeight: auto; // your computed value
height: 100%;
}
}
```

ScaleButton
```css
scalebutton::part(base) {
width: auto;
}
```

I am using this locally and you can check if you want to implement it in the package

**Comment by acstll** [comment]
For scale-button you can use the scoped variable `--width` (defaults to `auto`), inlined, like this:

```jsx
<ScaleButton style={{ '--width': '100%' }}>Click</ScaleButton>
```

Heights are a bit tricky, I don't think any element fills its parent height if not explicitly set to do so. So you're fix might do the trick.

Maybe you can use the `rows` attribute in the textarea to make it a bit larger instead of setting a fixed value?

**Comment by christopherGdynia** [comment]
@acstll thanks for your advise,

I got something wrong with the ScaleTextarea,
I got it working now

flex-auto, w-full, sm:w-1/2 are tailwind styles

I am setting a fixed height and saying with the class ```c-h``` (custom-height) to the elements to appy height auto.

```jsx
      className="flex-auto w-full sm:w-1/2 c-h"
                  style={{ height: 108 }}
                  label="Name"
                  value={model.name}
                  readonly
                />
```

```css
.c-h div textarea,
.c-h .textarea {
  height: 100%;
}
```
