### ISSUE TITLE
Differend disabled styles are in use 

### ISSUE THREAD

**Issue by Kaawo** [telekom/scale#603]
Greetings everyone, 

I noticed that there are different styles for disabled elements. For example, the checkbox has a colour value #CCCCCC (including the label). The colour value for disabled texts in the styling is 7F7F7F. 

If I see it correctly, this is due to the used --color-disabled: var(--scl-color-background-disabled).

This ensures that when we have disabled text and disabled labelled elements, they look different. Not good.

Or is there a reason for this that I have missed? :)

Thanks for helping.

Cheers.

**Comment by tommy-codez** [comment]
Hi there,
we also struggle with this topic at the moment (because the disabled elements are to bright)

What is the correct attribute for disabled date-picker elements ?!

**Comment by acstll** [comment]
Hey @tommy-codez :)

the current disabled color is by design. It's a tricky one because too little contrast against the normal color may not look disabled, but too much contrast (too bright) makes it hard to read and inaccessible.

We should make it easy for you to modify this color, but in the case of the date picker, it is not. We definitely need to improve that.

In `scale-text-field` there's a CSS variable to overwrite the default disabled color easily (`--color-disabled`), is this what you're looking for? or what did you mean by the "correct attribute"?

**Comment by tommy-codez** [comment]
Hi @acstll ,
yeah I looked for an attribute to change the disabled color for the date-picker

I played around with this in our app.css file but I am not sure if this is a good way to do it..

`scale-text-field {
  --scl-color-background-disabled: #999999;
}
scale-switch {
  --scl-color-background-disabled: #999999;
}`

the default disabled color is #cccccc ? - for some its to bright to read...

**Comment by acstll** [comment]
> the default disabled color is #cccccc ? - for some its to bright to read...

You are right. I agree with you here. But this is design decision *shrug*. We can re-evaluate it for sure (we have it in the backlog from this very ticket).

In the meantime, since the date picker is not using the shadow DOM, you can use some global CSS.

```css
/* Using a global variable here, the prefix is a suggestion */
:root {
  --scl-tommy-color-disabled: tomato;
}

.scale-date-picker.scale-date-picker--disabled,
.scale-date-picker.scale-date-picker--disabled input,
.scale-date-picker.scale-date-picker--disabled input:hover,
.scale-date-picker.scale-date-picker--disabled .duet-date__toggle,
.scale-date-picker.scale-date-picker--disabled .duet-date__toggle:hover,
.scale-date-picker.scale-date-picker--disabled .duet-date__toggle:hover scale-icon-content-calendar,
.scale-date-picker.scale-date-picker--disabled .date-picker__helper-text {
  border-color: var(--scl-tommy-color-disabled);
  color: var(--scl-tommy-color-disabled);
}

.scale-date-picker.scale-date-picker--disabled .date-picker__label {
  color: var(--scl-tommy-color-disabled);
}
```

---

> I played around with this in our app.css file but I am not sure if this is a good way to do it..

> `scale-text-field { --scl-color-background-disabled: #999999; } scale-switch { --scl-color-background-disabled: #999999; }`

This is one way to do it, if it works it's good 👍 But it shows that the "API" for this variables is inconsistent and can be improved (which is a good thing).

You can also do it like this:

```css
/* Both scale-text-field and scale-switch expose this `--color-disabled` variable */
scale-text-field,
scale-switch {
  --color-disabled: #999999;
}
```

I hope this helps, thanks for the feedback!
