### ISSUE TITLE
Button with a Loading Spinner

### ISSUE THREAD

**Issue by robertgebhard** [telekom/scale#722]
Hi guys,

in our portal users need to save, add and send a lot. This often results in long loading times. To let the user know that the system is working correctly we use full page Loading Spinner.

We would like to place a "Loading Spinner White Small" in the middle of a "Standard Button", so that the whole screen is not blocked by full page Loading Spinners.

Something simple like this: https://dev.to/dcodeyt/create-a-button-with-a-loading-spinner-in-html-css-1c0h

While building, we noticed that the spinner has a margin that makes it very difficult to just place the spinner in the middle of the button.

![Unknown](https://user-images.githubusercontent.com/95682620/145032420-2e2a23d3-5fb0-4694-9f8f-3dc119bc752b.png)

We also noticed that the margins are different between "Loading Spinner Standard" and "Loading Spinner White Small".

![Bildschirmfoto 2021-12-07 um 09 22 47](https://user-images.githubusercontent.com/95682620/145032865-7573fbff-dbf5-4f2e-83e3-dda45de654c4.png)

![Bildschirmfoto 2021-12-07 um 09 24 18](https://user-images.githubusercontent.com/95682620/145032885-2b0ea42e-0f85-4ca3-8477-0bb7399ff5c8.png)

Do you have any idea how we can get to the expected result?

Thanks!

**Comment by acstll** [comment]
Hello @robertgebhard thanks for asking and for the feedback.

The spinner definitely needs some more care regarding spacing. It shouldn't be hard to place it inside a button.

The margin values are currently hard-coded (we'll fix this), but you can use the ::part API to adjust the spacing. I put together this example that can hopefully serve as a starting point for you.

```css
/* Adjust colors */
scale-loading-spinner.within-button {
  --color-circle-primary: currentColor; /* same color as text */
  --color-circle-primary-inner: hsla(0deg 0% 0% / 0.2); /* black with opacity should work well on different background */
}

/* Adjust spacing with ::part */
scale-loading-spinner.within-button::part(container) {
  margin: 0;
  /* you can adjust these or add new declarations until you get the expected results */
  margin-top: -3px;
  padding-left: 10px;
}
```

```html
<!-- using icon-only on the button, could help -->
<scale-button icon-only>
  <scale-loading-spinner class="within-button"></scale-loading-spinner>
</scale-button>
```
