### ISSUE TITLE
Scale Modal --min-height-window

### ISSUE THREAD

**Issue by dillasyx** [telekom/scale#731]
In the scoped variables there is a --max-height-window, but why isn't there a possibility to set the min height of a modal?
In some cases this could be useful.

**Comment by acstll** [comment]
Thanks for asking @dillasyx 

It wasn't needed to make it work, and we try and avoid adding variables which are not strictly necessary.

When more "complex" customisation is needed, there's the ::part API. You can already do this:

```css
scale-modal::part(window) {
  min-height: 256px;
}
```

It's als possible to create new scope variables with this same technique (I wasn't aware of this until now 🤯) 

```css
scale-modal::part(window) {
  min-height: var(--min-height-window);
}
```

Having said that, I'm not against adding `--max-height-window`. In which cases would it be useful?
